### ISSUE TITLE
小细节

### ISSUE THREAD

**Issue by Baichenghui** [CoderJackyHuang/HYBHelperKit#3]
1.在HYBHelperKitBaseController.m文件中的方法实现:
-(void)hyb_setNavLeftImage:(id)image block:(HYBButtonBlock)block {
  UIImage *normalImage = image;

  if ([normalImage isKindOfClass:[NSString class]]) {
    normalImage = kImage(image);
  }
  /*\* ---------------------------------------------此处的image是否手误?--------*/
  UIButton *btn = [UIButton hyb_buttonWithImage:image
                                      superView:nil
                                    constraints:nil
                                        touchUp:block];

  [self _hyb_setNavItems:@[btn] isLeft:YES];
}
创建按钮的图片应该是 normalImage ,貌似手误写成 image了.

2.在UITextField+HYBMasonryKit.m文件中:
-(CGFloat)hyb_leftMarginOfCursor {
  NSNumber *number = objc_getAssociatedObject(self, _cmd);
  if ([number respondsToSelector:@selector(floatValue)]) {
    return [number floatValue];
  }
  return 8.0;
}

-(void)setHyb_leftMarginOfCursor:(CGFloat)hyb_leftMarginOfCursor {
  objc_setAssociatedObject(self,
                           _cmd,
                           @(hyb_leftMarginOfCursor),
                           OBJC_ASSOCIATION_RETAIN_NONATOMIC);
  if (self.leftView) {
    self.leftView.hyb_width = hyb_leftMarginOfCursor;
  }
}
的objc_getAssociatedObject(self,_cmd)和
objc_setAssociatedObject(self,
                           _cmd,
                           @(hyb_leftMarginOfCursor),
                           OBJC_ASSOCIATION_RETAIN_NONATOMIC);
使用_cmd作为key,这样会导致在set和get方法中key不一致.
经过测试,设置hyb_leftMarginOfCursor值,
然后通过提供的get方法获取,得到的是默认值8,与设置的值不一致

**Comment by CoderJackyHuang** [comment]
感谢提醒，现在已修改过来！
