### ISSUE TITLE
关于UIAlertView的分类

### ISSUE THREAD

**Issue by stevenlfg** [CoderJackyHuang/HYBHelperKit#5]
你好，看到了你写的的这个轮子，很棒。在我看到UIAlertView的分类时，想到了UIAlertView在9.0之后被弃用了，是否应该做个兼容呢？谢谢！另外，作者能否针对每个工具类都有一个实例的应用，这样方便开发者更快地掌握。

**Comment by CoderJackyHuang** [comment]
实例的话后续有足够时间才去做哦，目前在找工作中，只能简单维护一下！等稳定下来才能完善！

**Comment by stevenlfg** [comment]
好的，谢谢！
